// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $ai from "./routes/ai.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $canadaland_submission from "./routes/canadaland-submission.tsx";
import * as $canadaland from "./routes/canadaland.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $dev from "./routes/dev.tsx";
import * as $frontmatter from "./routes/frontmatter.tsx";
import * as $give_quebec_back from "./routes/give-quebec-back.tsx";
import * as $graveyard_farms from "./routes/graveyard-farms.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $justin_trudeau from "./routes/justin-trudeau.tsx";
import * as $list_of_jobs from "./routes/list-of-jobs.tsx";
import * as $maid_expansion from "./routes/maid-expansion.tsx";
import * as $markdown_cheat_sheet from "./routes/markdown-cheat-sheet.tsx";
import * as $markdown_syntax from "./routes/markdown-syntax.tsx";
import * as $now from "./routes/now.tsx";
import * as $obsidino from "./routes/obsidino.tsx";
import * as $payments from "./routes/payments.tsx";
import * as $pierre_poilievre from "./routes/pierre-poilievre.tsx";
import * as $pierre_youtube_analysis_1 from "./routes/pierre-youtube-analysis-1.tsx";
import * as $politics from "./routes/politics.tsx";
import * as $security_guard_course from "./routes/security-guard-course.tsx";
import * as $the_pretendian_crisis from "./routes/the-pretendian-crisis.tsx";
import * as $tims_twos from "./routes/tims-twos.tsx";
import * as $unity_party from "./routes/unity-party.tsx";
import * as $web_app_dev from "./routes/web-app-dev.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/ai.tsx": $ai,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/canadaland-submission.tsx": $canadaland_submission,
    "./routes/canadaland.tsx": $canadaland,
    "./routes/contact.tsx": $contact,
    "./routes/dev.tsx": $dev,
    "./routes/frontmatter.tsx": $frontmatter,
    "./routes/give-quebec-back.tsx": $give_quebec_back,
    "./routes/graveyard-farms.tsx": $graveyard_farms,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/justin-trudeau.tsx": $justin_trudeau,
    "./routes/list-of-jobs.tsx": $list_of_jobs,
    "./routes/maid-expansion.tsx": $maid_expansion,
    "./routes/markdown-cheat-sheet.tsx": $markdown_cheat_sheet,
    "./routes/markdown-syntax.tsx": $markdown_syntax,
    "./routes/now.tsx": $now,
    "./routes/obsidino.tsx": $obsidino,
    "./routes/payments.tsx": $payments,
    "./routes/pierre-poilievre.tsx": $pierre_poilievre,
    "./routes/pierre-youtube-analysis-1.tsx": $pierre_youtube_analysis_1,
    "./routes/politics.tsx": $politics,
    "./routes/security-guard-course.tsx": $security_guard_course,
    "./routes/the-pretendian-crisis.tsx": $the_pretendian_crisis,
    "./routes/tims-twos.tsx": $tims_twos,
    "./routes/unity-party.tsx": $unity_party,
    "./routes/web-app-dev.tsx": $web_app_dev,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
