

export default function Home() {
    
    return (<div class="main text-left w-max-md mx-auto">
        
    <h1>Frontmatter</h1>
<p>How does this look on your end, My Dearest Deno?</p>
<h2>integrate frontmatter</h2>
<p>I'd like to use Fresh component to consume props generated by frontmatter.</p>
<p>How can I accomplish that?</p>


</div>);
}
